### PR TITLE
finally doing this right?

### PR DESCRIPTION
**Pull request by benflinn**

### CODE REVIEW

**Comment by abraxasrex** [comment]
Just so u know I won't get to deploy the app until this afternoon/tonight ; gotta do some family stuff

**Comment by benflinn** [comment]
sounds good, that's fine. hey - i woke up this morning and realized i could
work on the color scheme, background image, and the layout quite a bit.
(not even using bootstrap layout..)

so i'll work on that a little this afternoon and we can talk more about it

**Comment by abraxasrex** [comment]
Sure; go crazy

**Comment by abraxasrex** [comment]
Hey, my screenhero is not working right. anyway, let's merge our changes
and deploy this afternoon; i'll push my latest to remote now.

One thing though, I really want to figure out the text overflow if you have
any ideas. I tried using word-wrap-break-word and some other css tricks to
no avail.

**Comment by benflinn** [comment]
Great! I changed the layout - have you seen that? I think it helped fix the
text issue, at least partially.

Alternatively I think you can use css to make the div 300 pixels wide, that
should cause it to wrap properly

**Comment by benflinn** [comment]
Also we can talk on skype if necessary, my username is ben.linn85

**Comment by abraxasrex** [comment]
i invited you to hangoutbut what i just pushed to remote is pretty much the
last thing.

although.....it seems like if a picture isn't found, it doesn't return the
result as a whole

**Comment by abraxasrex** [comment]
pull requested

**Pull request merged**
